### ISSUE TITLE
Package Download

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#19]
### User story

_As a user of the Middleware Launcher, I want the Launcher to be able to automatically download packages, so that I don't have to download them myself and they can be updated._

Topics that should be covered:
- ponfig download
- package download
- package cache
- package server concept

**Comment by mijomilicevic** [comment]
Who will do the Download? The Launcher or the ProcessHost?

**Comment by TSchmiedlechner** [comment]
I'd handle the download in the Launcher. Not so much because of any technical reasons, but it seems nicer process-wise IMO - otherwise, we'd have the download scattered over multiple processes, and technically someone could disconnect the internet after the SCU started and prevent the start of the Queue. 

I have a slightly better feeling about doing these things sequentially to simplify error handling 😅 
Like: 
- Config download ✅
- Package download ✅
- Startup ❌

**Comment by TSchmiedlechner** [comment]
Also, if we'd use a package cache, we should think of somehow validating that files were not altered manually, as this would be a potentially easy way to tamper executables.

We could e.g. do this by introducing a checksum for each package, or by validating in the Launcher if the used DLLs are correctly signed by us?
